version: '1'

services:
  web:
    build:
      context: .
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    expose:
      - 8081 
    depends_on:
      - postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./mysqlData:/mysqlData   
  

  redis:
    image: redis
    restart: always


  postgres: 
    image: "postgres:15.2"
    container_name: postgresql
    ports:
      - "8081:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    volumes:
      - db_data_dev:/var/lib/postgresql/data


volumes:
  db_data_dev:











      

